name: Deploy App Service
on:
  workflow_dispatch:

jobs:
  deploy-appservice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Deploy App Service
      - name: Deploy App Service
        id: appservice
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: northeurope
          template: ./deploy/main.bicep
          parameters: ./deploy/deploy.parameters.json
      
      # Set Secret with websitename value
      - name: Set Github secret
        uses: gliech/create-github-secret-action@v1
        with:
          name: WEBSITENAME
          value: ${{ steps.appservice.outputs.webSiteName }}
          pa_token: ${{ secrets.PA_TOKEN }}